version: '3.3'
networks:
  onlyoffice:
    driver: bridge
volumes:
  document_data: null
  document_log: null
  document_forgotten: null
  community_data: null
  community_log: null
  mysql_data: null
  nextcloud: null
  moodle: null
services:
  mysql:
    container_name: mysql
    image: 'mysql:5.7.20'
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    networks:
      - onlyoffice
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - './config/mysql/conf.d:/etc/mysql/conf.d'
      - './config/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
      - 'mysql_data:/var/lib/mysql'
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: 'onlyoffice/documentserver:latest'
    stdin_open: true
    tty: true
    restart: always
    networks:
      - onlyoffice
    environment:
      - VIRTUAL_HOST=onlyoffice-document.test
    expose:
      - '80'
      - '443'
    volumes:
      - 'document_data:/var/www/onlyoffice/Data'
      - 'document_log:/var/log/onlyoffice'
      - './document_fonts:/usr/share/fonts/truetype/custom'
      - 'document_forgotten:/var/lib/onlyoffice/documentserver/App_Data/cache/files/forgotten'
  nginx-proxy:
    container_name: nginx-proxy
    image: 'jwilder/nginx-proxy:alpine'
    stdin_open: true
    tty: true
    restart: always
    ports:
      - '80:80'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
    networks:
      - onlyoffice
  nextcloud:
    container_name: nextcloud
    image: 'nextcloud:apache'
    environment:
      - VIRTUAL_HOST=nextcloud.test
      - MYSQL_HOST=mysql
      - MYSQL_PASSWORD=nextcloud_pass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud_user
    expose:
      - '80'
      - '443'
    depends_on:
      - mysql
      - nginx-proxy
    volumes:
      - 'nextcloud:/var/www/html'
    stdin_open: true
    tty: true
    restart: always
    networks:
      - onlyoffice
  moodle:
    container_name: moodle
    build:
      context: ../docker-moodle
      dockerfile: Dockerfile
    image: 'moodle:v34'
    environment:
      - VIRTUAL_HOST=moodle.test
      - MYSQL_HOST=mysql
      - MYSQL_PASSWORD=moodle_pass
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle_user
    expose:
      - '80'
      - '443'
    depends_on:
      - mysql
      - nginx-proxy
    volumes:
      - 'moodle:/moodle/data'
      - './moodle-config.php:/var/www/html/config.php:ro'
    stdin_open: true
    tty: true
    restart: always
    networks:
      - onlyoffice
